### ISSUE TITLE
How to install this project?

### ISSUE THREAD

**Issue by thinkh** [spatie/dashboard.spatie.be#7]
Thanks for this nice piece of work. I would like to try it, but I don't know how to install it. Could you please provide the basic steps/commands to install it?

**Comment by freekmurze** [comment]
It's just a regular Laravel project. After cloning it you should run these commands:

```
composer install
npm install
gulp
```

You should copy `.env.example` to `.env` and fill in the variables with the credentials of your services.

**Comment by thinkh** [comment]
@freekmurze Thanks.

**Comment by ligne13** [comment]
Hi @freekmurze,
I'm having errors when running npm install (see the end of log).

```
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
-
> node-sass@3.10.1 install ~/dashboard.spatie.be/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

Start downloading binary at https://github.com/sass/node-sass/releases/download/v3.10.1/darwin-x64-46_binding.node
Binary downloaded and installed at ~/dashboard.spatie.be/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64-46/binding.node

> node-sass@3.10.1 postinstall ~/dashboard.spatie.be/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

"~/dashboard.spatie.be/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64-46/binding.node" exists. 
 testing binary.
Binary is fine; exiting.

> fsevents@1.0.14 install ~/dashboard.spatie.be/node_modules/laravel-elixir/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "~/dashboard.spatie.be/node_modules/laravel-elixir/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> fsevents@1.0.14 install ~/dashboard.spatie.be/node_modules/laravel-elixir/node_modules/watchify/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "~/dashboard.spatie.be/node_modules/laravel-elixir/node_modules/watchify/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> fsevents@1.0.14 install ~/dashboard.spatie.be/node_modules/laravel-elixir/node_modules/browser-sync/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "~/dashboard.spatie.be/node_modules/laravel-elixir/node_modules/browser-sync/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
npm ERR! Darwin 15.6.0
npm ERR! argv "~/.nvm/versions/node/v4.4.7/bin/node" "~/.nvm/versions/node/v4.4.7/bin/npm" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! file ~/.npm/balanced-match/0.4.2/package/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! No data, empty input at 1:1
npm ERR! 
npm ERR! ^
npm ERR! File: ~/.npm/balanced-match/0.4.2/package/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     ~/dashboard.spatie.be/npm-debug.log
```

And logically, I can't run gulp:

```
[10:04:58] Using gulpfile ~/dashboard.spatie.be/gulpfile.js
[10:04:58] Starting 'default'...
[10:04:58] Starting 'browserify'...
[10:04:58] 'browserify' errored after 444 ms
[10:04:58] Error: Cannot find module 'vueify'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at ~/dashboard.spatie.be/node_modules/laravel-elixir/tasks/browserify.js:90:13
    at Array.forEach (native)
    at browserifyStream (~/dashboard.spatie.be/node_modules/laravel-elixir/tasks/browserify.js:88:39)
    at null.definition (~/dashboard.spatie.be/node_modules/laravel-elixir/tasks/browserify.js:54:13)
    at Task.run (~/dashboard.spatie.be/node_modules/laravel-elixir/Task.js:94:17)
    at Gulp.<anonymous> (~/dashboard.spatie.be/node_modules/laravel-elixir/index.js:89:52)
[10:04:58] Error in plugin 'run-sequence(browserify)'
Message:
    Cannot find module 'vueify'
Details:
    code: MODULE_NOT_FOUND
Stack:
Error: Cannot find module 'vueify'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at ~/dashboard.spatie.be/node_modules/laravel-elixir/tasks/browserify.js:90:13
    at Array.forEach (native)
    at browserifyStream (~/dashboard.spatie.be/node_modules/laravel-elixir/tasks/browserify.js:88:39)
    at null.definition (~/dashboard.spatie.be/node_modules/laravel-elixir/tasks/browserify.js:54:13)
    at Task.run (~/dashboard.spatie.be/node_modules/laravel-elixir/Task.js:94:17)
    at Gulp.<anonymous> (~/dashboard.spatie.be/node_modules/laravel-elixir/index.js:89:52)
[10:04:58] Finished 'default' after 451 ms
```

thanks

**Comment by sebastiandedeyne** [comment]
Hi @ligne13 

That seems to be an issue with npm, or the `balanced-match` package that gets pulled in, I'm not sure if we'll be able to help with that one :/

You could always pull in the `vue2` branch of this package instead, which uses a whole new set of dependencies. It's not released yet, but will be merged to master as the new version some time next week, so you might as well give it a try!
